# Generated by Django 5.2.5 on 2025-09-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='tax_id',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/bank_doc/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_license_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/business_license/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('service_provider', 'Service Provider'), ('grocery', 'Grocery Store'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('bakery', 'Bakery')], default='retailer', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='fssai_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/fssai_license/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/gst_certificate/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pincode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VendorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('address', 'Address'), ('banking', 'Banking')], max_length=20)),
                ('new_address', models.TextField(blank=True, null=True)),
                ('new_city', models.CharField(blank=True, max_length=100, null=True)),
                ('new_state', models.CharField(blank=True, max_length=100, null=True)),
                ('new_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('new_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_account_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('new_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('new_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='accounts.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='vendor_docs/additional/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_docs', to='accounts.vendorprofile')),
            ],
        ),
    ]
