# Generated by Django 5.2.5 on 2025-09-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_tax_id_vendorprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
