# Generated by Django 5.2.5 on 2025-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendorprofile_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='bank_account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bulk_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_license_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='employee_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='established_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='free_delivery_above',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='friday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='fssai_license_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_certificate_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='home_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='loyalty_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='monday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='online_ordering',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='saturday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='sunday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='thursday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tuesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='wednesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='document',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_license_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='fssai_license',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='gst_certificate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
