# Generated by Django 5.2.5 on 2025-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendorprofile_bank_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='status_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='status_override_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
