# Generated by Django 5.2.5 on 2025-09-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='track_quantity',
        ),
    ]
