# Generated by Django 5.2.5 on 2025-09-10 05:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_product_compare_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=accounts.models.product_image_upload_path),
        ),
    ]
