# Generated by Django 5.2.5 on 2025-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_delivery_boy_phone_order_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='appeal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='esewa_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='khalti_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='refund_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank Transfer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('appeal', 'Appeal'), ('processed', 'Processed'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
